version: '3.9'

services:
  app:
    build: .
    container_name: webhook_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://webhook:webhook@postgres:5432/webhookdb
      GITHUB_SECRET: supersecret
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: webhook_postgres
    restart: always
    environment:
      POSTGRES_USER: webhook
      POSTGRES_PASSWORD: webhook
      POSTGRES_DB: webhookdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
